import {normalizePreferences} from './preferences.js';
import {BookmarkLibrary, normalizeMeta,searchBookmarks,safeUrl} from './library.js';
import {makeExport,parseImport,importAdditive,cleanupCandidates} from './transfer.js';
import {recordOperation,undoOperation} from './recovery.js';
import {enableAI,disableAI,suggestBookmarks,enableDrive,disableDrive,uploadBackup,listBackups,downloadBackup,deleteBackup} from './integrations.js';
const lib=new BookmarkLibrary(chrome),app=document.querySelector('#app'),narrow=matchMedia('(max-width:760px)');let mobileTreeOpen=false;const systemDark=matchMedia('(prefers-color-scheme: dark)');
let state,filter={query:'',folder:'',tag:'',domain:'',favorites:false},selected=new Set(),limit=100,mode='grid',sortMode='manual',treeOpen=true,refreshVersion=0,dragIds=[],prefs={},collapsed=new Set();
let settingsOpen=false,libraryScroll=0;
const preview=document.documentElement.dataset.preview==='true',initialTitle=location.pathname.endsWith('/settings.html')?'1stTab Bookmarks':document.title;
const libraryURL=(()=>{const url=new URL(location.pathname.endsWith('/settings.html')?chrome.runtime.getURL('manager.html'):location.href);url.hash='';if(preview)url.searchParams.delete('settings');return url.href})();
const isSettingsRoute=()=>preview?location.hash==='#settings':location.pathname.endsWith('/settings.html');
function el(tag,attrs={},...children){const n=document.createElement(tag);for(const[k,v]of Object.entries(attrs)){if(k.startsWith('on'))n.addEventListener(k.slice(2).toLowerCase(),v);else if(k==='class')n.className=v;else if(k==='text')n.textContent=v;else if((k.startsWith('aria-')||k==='draggable')&&typeof v==='boolean')n.setAttribute(k,String(v));else if(v!==false&&v!=null)n.setAttribute(k,v===true?'':v)}for(const c of children.flat())if(c!=null)n.append(typeof c==='string'?document.createTextNode(c):c);return n;}
const installedVersion=chrome.runtime.getManifest?.().version||'';const brandName=installedVersion?`1stTab bookmark manager, version ${installedVersion}`:'1stTab bookmark manager';
function versionTag(){return installedVersion?el('small',{class:'brand-version',title:'Installed version'},`v${installedVersion}`):null;}
const button=(text,click,attrs={})=>el('button',{type:'button',onclick:()=>run(click),...attrs},text);

const paths={search:['M21 21l-4.5-4.5','M18 10a8 8 0 1 1-16 0 8 8 0 0 1 16 0'],plus:['M12 5v14','M5 12h14'],folder:['M3 7a2 2 0 0 1 2-2h4l2 2h8a2 2 0 0 1 2 2v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z'],chevron:['M9 5l7 7-7 7'],star:['m12 3 2.8 5.7 6.2.9-4.5 4.4 1.1 6.2L12 17.3l-5.6 2.9 1.1-6.2L3 9.6l6.2-.9z'],edit:['m16 3 5 5-12 12-6 1 1-6z','m14 5 5 5'],trash:['M3 6h18','M9 6V3h6v3','M5 6l1 15h12l1-15','M10 10v7','M14 10v7'],grid:['M3 3h7v7H3z','M14 3h7v7h-7z','M3 14h7v7H3z','M14 14h7v7h-7z'],list:['M8 5h13','M8 12h13','M8 19h13','M3 5h.01','M3 12h.01','M3 19h.01'],external:['M14 3h7v7','M21 3l-9 9','M10 3H5a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-5'],moon:['M21 12.8A9 9 0 1 1 11.2 3 7 7 0 0 0 21 12.8z'],bookmark:['M6 3h12v18l-6-4-6 4z'],sidebar:['M3 4h18v16H3z','M9 4v16'],sliders:['M4 6h16','M4 12h16','M4 18h16','M8 3v6','M16 9v6','M10 15v6'],settings:['M12 8a4 4 0 1 0 0 8 4 4 0 0 0 0-8','m9.5 2-.6 2.5-2 1.2-2.5-.7-2.5 4.3 1.9 1.8v2.4l-1.9 1.8 2.5 4.3 2.5-.7 2 1.2.6 2.5h5l.6-2.5 2-1.2 2.5.7 2.5-4.3-1.9-1.8v-2.4l1.9-1.8L19.6 5l-2.5.7-2-1.2-.6-2.5z'],lock:['M7 10V7a5 5 0 0 1 10 0v3','M5 10h14v11H5z'],drag:['M8 5h.01','M16 5h.01','M8 12h.01','M16 12h.01','M8 19h.01','M16 19h.01'],more:['M5 12h.01','M12 12h.01','M19 12h.01'],undo:['M3 10h7','M3 10V3','M3 10a9 9 0 1 1 2 9'],tag:['M3 3h8l10 10-8 8L3 11z','M7 7h.01'],close:['M6 6l12 12','M6 18 18 6'],up:['M12 20V4','M5 11l7-7 7 7'],down:['M12 4v16','M5 13l7 7 7-7'],export:['M12 15V3','M7 8l5-5 5 5','M4 15v6h16v-6'],import:['M12 3v12','M7 10l5 5 5-5','M4 15v6h16v-6'],history:['M3 10a9 9 0 1 1 1 7','M3 3v7h7','M12 7v5l3 2'],cleanup:['M4 7h16','M7 7l1 14h8l1-14','M9 3h6']};
function glyph(name){const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');for(const[k,v]of Object.entries({width:'15',height:'15',viewBox:'0 0 24 24',fill:'none',stroke:'currentColor','stroke-width':'1.8','stroke-linecap':'round','stroke-linejoin':'round','aria-hidden':'true'}))svg.setAttribute(k,v);if(name==='drag')svg.setAttribute('stroke-width','3');for(const d of paths[name]||paths.folder){const p=document.createElementNS(svg.namespaceURI,'path');p.setAttribute('d',d);svg.append(p)}return svg}
function iconButton(label,icon,click,attrs={}){return button([glyph(icon),el('span',{class:'sr-only'},label)],click,{'aria-label':label,title:label,class:'icon-button',...attrs});}

function message(text,error=false){const n=document.querySelector('#status');if(!n){app.textContent=text;return}n.textContent=text;n.className=error?'status error':'sr-only';document.querySelectorAll('.dialog-error').forEach(e=>e.remove());const d=[...document.querySelectorAll('dialog[open]')].at(-1);if(error&&d)d.querySelector('form')?.append(el('p',{class:'dialog-error',role:'alert'},text));}
const tracked=(label,fn)=>recordOperation(lib,label,fn);
async function run(fn){try{await fn()}catch(e){message(e.message,true)}}
async function refresh(){const v=++refreshVersion;const s=await lib.load();if(v!==refreshVersion)return;state=s;if(filter.folder&&!state.nodes.has(filter.folder))filter.folder='';for(const id of selected)if(!state.nodes.has(id))selected.delete(id);renderResults();renderFolders();}
function writableFolders(){return state.folders.filter(n=>n.parentId&&!n.managed)}
function folderSelect(value=''){const s=el('select',{'aria-label':'Destination folder'});for(const f of writableFolders())s.append(el('option',{value:f.id},f.title||'Untitled folder'));if(value)s.value=value;return s;}
function modal(title,build){const d=el('dialog',{'aria-label':title});const form=el('form',{method:'dialog'});form.append(el('h2',{},title));const parts=build(d,form);form.append(el('div',{class:'dialog-actions'},button('Cancel',()=>d.close()),parts));d.append(form);document.body.append(d);d.addEventListener('close',()=>d.remove());d.addEventListener('cancel',()=>{});d.showModal();return d;}
function field(label,input){return el('label',{},label,input)}
function editBookmark(node=null,draft=null){modal(node?'Edit bookmark':'Save bookmark',(dialog,form)=>{const title=el('input',{required:true,maxlength:500,value:node?.title||draft?.title||''});const url=el('input',{required:true,value:node?.url||draft?.url||'',placeholder:'https://example.com'});const destination=folderSelect(node?.parentId||filter.folder);const m=normalizeMeta(state.metadata[node?.id]);const tags=el('input',{value:m.tags.join(', '),maxlength:2400,placeholder:'research, work'}),note=el('textarea',{rows:4,maxlength:10000},m.note);const pinned=el('input',{type:'checkbox',checked:m.pinned});form.append(field('Title',title),field('URL',url),field('Folder',destination),field('Tags, separated by commas',tags),field('Note about this bookmark',note),field('Favorite',pinned));return button('Save',async()=>{if(!form.reportValidity())return;safeUrl(url.value);await tracked('Save bookmark',async()=>{if(node&&node.parentId!==destination.value)await lib.move([node.id],destination.value);const n=node?await lib.update(node.id,{title:title.value,url:url.value}):await lib.create({parentId:destination.value,title:title.value,url:url.value});await lib.setMeta(n.id,{...m,tags:tags.value.split(','),note:note.value,pinned:pinned.checked});});dialog.close();await refresh();message('Bookmark saved.');},{class:'primary'})});}
function editFolder(node=null,parentId=''){modal(node?'Edit folder':'New folder',(dialog,form)=>{const title=el('input',{required:true,maxlength:500,value:node?.title||''}),dest=folderSelect(node?.parentId||parentId||filter.folder);form.append(field('Folder name',title));if(!node)form.append(field('Parent folder',dest));return button('Save',async()=>{if(!form.reportValidity())return;await tracked('Save folder',async()=>{if(node)await lib.update(node.id,{title:title.value});else await lib.create({parentId:dest.value,title:title.value});});dialog.close();await refresh();message('Collection saved.');},{class:'primary'})});}
function previewMove(ids){if(!ids.length)throw Error('Select bookmarks to move.');modal(`Move ${ids.length} item(s)`,(dialog,form)=>{const dest=folderSelect();form.append(el('p',{},'A local snapshot will be saved before moving these items.'),field('Destination',dest));return button('Confirm move',async()=>{await tracked('Move items',()=>lib.move(ids,dest.value));selected.clear();dialog.close();await refresh();message('Items moved. Recovery snapshot retained.');},{class:'primary'})});}
function previewDelete(ids){if(!ids.length)throw Error('Select items to delete.');modal(`Delete ${ids.length} item(s)?`,(dialog,form)=>{form.append(el('p',{},'Folders include their contents. A local recovery snapshot will be saved first.'),el('ul',{},ids.slice(0,10).map(id=>el('li',{},state.nodes.get(id)?.title||id))));return button('Confirm delete',async()=>{await tracked('Delete items',()=>lib.remove(ids));selected.clear();dialog.close();await refresh();message('Deleted. Recovery snapshot retained.');},{class:'danger'})});}
function exportFile(doc,name){const u=URL.createObjectURL(new Blob([JSON.stringify(doc,null,2)],{type:'application/json'}));const a=el('a',{href:u,download:name});a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
function previewImport(doc){modal(`Import ${doc.counts.bookmarks} bookmarks and ${doc.counts.folders} folders`,(dialog,form)=>{const dest=folderSelect();form.append(el('p',{},'Adds the imported folders and bookmarks directly to the destination folder. Existing bookmarks will not be overwritten. A local snapshot is saved first.'),field('Destination',dest));return button('Confirm import',async()=>{const n=await tracked('Import bookmarks',()=>importAdditive(lib,doc,dest.value));dialog.close();await refresh();message(`Imported ${n} items.`);},{class:'primary'})});}
async function restoreSnapshot(){const data=await chrome.storage.local.get('bookmarks.lastBackup.v1');const backup=data['bookmarks.lastBackup.v1'];if(!backup)throw Error('No pre-edit snapshot is available yet.');previewImport(parseImport(JSON.stringify(makeExport(backup))));}
function cleanup(){const c=cleanupCandidates(state.tree);modal('Review duplicate links',(dialog,form)=>{form.append(el('p',{},`${c.duplicates.length} exact-URL duplicate groups; ${c.emptyFolders.length} empty folders. No automatic deletion.`));const ids=new Set();for(const group of c.duplicates.slice(0,100)){form.append(el('h3',{},group[0].url));for(const b of group.slice(1)){const check=el('input',{type:'checkbox',disabled:b.managed,onchange:e=>e.target.checked?ids.add(b.id):ids.delete(b.id)});form.append(field(`${b.title} — ${state.nodes.get(b.parentId)?.title}`,check))}}for(const f of c.emptyFolders){try{lib.editable(state,f.id)}catch{continue}const check=el('input',{type:'checkbox',onchange:e=>e.target.checked?ids.add(f.id):ids.delete(f.id)});form.append(field(`Empty folder: ${f.title}`,check))}return button('Review selected deletions',()=>{if(!ids.size)throw Error('Select items to review.');dialog.close();previewDelete([...ids])})});}
function chooseCollection(id='',favorites=false){filter.folder=id;filter.favorites=favorites;limit=100;document.querySelector('#favorites-filter').checked=favorites;renderResults();renderFolders();}
async function savePrefs(){prefs={...prefs,view:mode,sort:sortMode,treeOpen,collapsed:[...collapsed]};await chrome.storage.local.set({'bookmarks.preferences.v1':prefs});}
function applyPrefs(value={}){prefs=normalizePreferences(value);mode=prefs.view;sortMode=prefs.sort;treeOpen=prefs.treeOpen;collapsed=new Set(prefs.collapsed);applyAppearance();syncSettings();syncFilters();if(state){renderResults();renderFolders();}}
function applyAppearance(){const root=document.documentElement;root.dataset.theme=prefs.theme==='system'?(systemDark.matches?'dark':'light'):prefs.theme;root.dataset.design=prefs.design;root.dataset.gridShape=prefs.gridShape;root.style.setProperty('--sidebar-width',`${prefs.sidebarWidth}px`);syncResizeHandle();root.dataset.density=prefs.density;root.dataset.showNotes=String(prefs.showNotes);root.dataset.reduceMotion=String(prefs.reduceMotion);root.dataset.largeUi=String(prefs.textScale>=1.2||prefs.iconScale>=1.3);root.style.setProperty('--text-scale',String(prefs.textScale));root.style.setProperty('--icon-scale',String(prefs.iconScale));root.style.setProperty('--navigation-scale',String(Math.min(1.35,Math.max(1,prefs.textScale,prefs.iconScale))));}
function syncFilters(){const tray=document.querySelector('#filter-tray'),toggle=document.querySelector('#filters-toggle');if(!tray||!toggle)return;const open=prefs.filtersOpen===true,active=[filter.folder,filter.tag.trim(),filter.domain.trim(),filter.favorites].filter(Boolean).length;tray.hidden=!open;toggle.setAttribute('aria-expanded',String(open));toggle.setAttribute('aria-label',open?'Hide filters':'Show filters');toggle.title=open?'Hide filters':'Show filters';toggle.classList.toggle('has-active-filters',active>0);document.querySelector('#filters-toggle-label').textContent=open?'Hide filters':'Show filters';const badge=document.querySelector('#filters-active-count');badge.textContent=String(active);badge.hidden=!active;document.querySelector('#filters-summary').textContent=active?`${active} active filter${active===1?'':'s'}. Hiding the controls keeps filters applied.`:'No active filters.';}
async function changePreference(patch){applyPrefs({...prefs,...patch});await savePrefs();}
function syncSettings(){const form=document.querySelector('#workspace-settings');if(!form)return;for(const key of['theme','textScale','iconScale','view','sort','density']){const control=form.elements.namedItem(key);if(control&&control!==document.activeElement)control.value=String(prefs[key])}for(const key of['showNotes','reduceMotion'])form.elements.namedItem(key).checked=prefs[key];for(const key of['design','gridShape'])for(const input of form.querySelectorAll(`[name="${key}"]`))input.checked=input.value===prefs[key];for(const key of['textScale','iconScale'])form.querySelector(`[data-output="${key}"]`).textContent=`${Math.round(prefs[key]*100)}%`;const demo=form.querySelector('.settings-sample');demo.dataset.design=prefs.design;}
function buildSettingsPage(){const page=el('section',{id:'settings-page',class:'settings-page',hidden:true,'aria-labelledby':'settings-title'}),form=el('form',{id:'workspace-settings',onsubmit:e=>e.preventDefault()});const dialog={close:()=>showLibrary()};form.append(el('p',{class:'settings-intro'},'Make this space feel like yours. Changes save automatically on this device.'));
const designs=[['prism','Prism','Violet & ink'],['atelier','Atelier','Warm & editorial'],['studio','Studio','Clean & precise'],['pop','Pop','Playful & graphic'],['enterprise','Enterprise','Focused & professional']];const themeGrid=el('div',{class:'theme-grid',role:'group','aria-label':'Design theme'});for(const[value,title,description]of designs){const input=el('input',{type:'radio',name:'design',value,checked:prefs.design===value,onchange:()=>run(()=>changePreference({design:value}))});themeGrid.append(el('label',{class:'theme-choice'},input,el('span',{class:`theme-swatch ${value}`,'aria-hidden':'true'},el('span',{class:'swatch-sidebar'}),el('span',{class:'swatch-cards'},el('i'),el('i'),el('i'),el('i'))),el('strong',{},title),el('small',{},description)))}
function selectPreference(name,label,options){const select=el('select',{name,'aria-label':label,onchange:e=>run(()=>changePreference({[name]:e.target.value}))},options.map(([value,title])=>el('option',{value},title)));select.value=String(prefs[name]);return field(label,select)}
function scaleControl(name,label,description,max){const input=el('input',{type:'range',name,min:.9,max,step:.1,value:prefs[name],'aria-label':label,oninput:e=>run(()=>changePreference({[name]:Number(e.target.value)}))});return el('div',{class:'size-setting'},el('div',{class:'setting-heading'},el('div',{},el('label',{'for':`setting-${name}`},label),el('p',{},description)),el('output',{'data-output':name,for:`setting-${name}`},`${Math.round(prefs[name]*100)}%`)),el('div',{class:'size-controls'},el('span',{'aria-hidden':'true'},name==='textScale'?'A':glyph('grid')),Object.assign(input,{id:`setting-${name}`}),el('span',{class:'size-large','aria-hidden':'true'},name==='textScale'?'A':glyph('grid'))));}
function togglePreference(name,label,description){const input=el('input',{type:'checkbox',name,checked:prefs[name],onchange:e=>run(()=>changePreference({[name]:e.target.checked}))});return el('label',{class:'toggle-setting'},el('span',{},el('strong',{},label),el('small',{},description)),input)}
form.append(el('section',{class:'settings-section',id:'settings-appearance'},el('div',{class:'settings-section-title'},glyph('moon'),el('h3',{},'Appearance')),themeGrid,selectPreference('theme','Color mode',[['light','Light'],['dark','Dark'],['system','Follow system']])));
form.append(el('section',{class:'settings-section',id:'settings-sizing'},el('div',{class:'settings-section-title'},glyph('sliders'),el('h3',{},'Text & icons')),scaleControl('textScale','Text size','Make titles, labels and notes easier to read.',1.4),scaleControl('iconScale','Icon size','Enlarge bookmark icons and action controls.',1.5),el('div',{class:'settings-sample'},el('div',{class:'sample-tile'},glyph('bookmark')),el('div',{},el('strong',{},'A clearer view of your library'),el('span',{},'Your changes appear immediately.')),el('span',{class:'sample-tag'},'Preview'))));
form.append(el('section',{class:'settings-section',id:'settings-workspace'},el('div',{class:'settings-section-title'},glyph('grid'),el('h3',{},'Workspace')),el('div',{class:'settings-columns'},selectPreference('view','Bookmark view',[['grid','Cards'],['list','List']]),selectPreference('sort','Default sort',[['manual','Manual order'],['title','Name A–Z'],['newest','Newest first']])),selectPreference('density','Spacing',[['comfortable','Comfortable'],['compact','Compact']]),togglePreference('showNotes','Show bookmark notes','Display the note beneath each bookmark title.'),togglePreference('reduceMotion','Reduce motion','Keep the interface still when hovering and switching views.')));
const shapeGrid=el('div',{class:'shape-grid',role:'group','aria-label':'Card shape'});for(const[value,title]of[['rectangle','Rectangle'],['square','Square'],['rounded','Rounded'],['circle','Circle'],['sphere','Sphere']])shapeGrid.append(el('label',{class:'shape-choice'},el('input',{type:'radio',name:'gridShape',value,checked:prefs.gridShape===value,onchange:()=>run(()=>changePreference({gridShape:value}))}),el('span',{class:`shape-swatch ${value}`,'aria-hidden':'true'},glyph('bookmark')),el('strong',{},title)));
form.append(el('section',{class:'settings-section',id:'settings-shapes'},el('div',{class:'settings-section-title'},glyph('grid'),el('h3',{},'Card shapes')),el('p',{class:'setting-help'},'Choose the silhouette of your bookmark cards. List view stays compact.'),shapeGrid,button('Preview in card view',async()=>{await changePreference({view:'grid'});showLibrary()},{class:'secondary'})));
form.append(libraryToolsSection(dialog));
form.append(el('div',{class:'settings-footer'},button('Reset appearance',()=>changePreference({design:'enterprise',theme:'light',textScale:1,iconScale:1,density:'comfortable',showNotes:true,reduceMotion:false,gridShape:'rectangle',sidebarWidth:270}),{class:'reset-appearance'}),el('span',{},`1stTab${chrome.runtime.getManifest?.().version?' v'+chrome.runtime.getManifest().version:''} · Saved automatically on this device`)));
const nav=el('nav',{class:'settings-nav','aria-label':'Settings sections'});for(const[id,label]of[['appearance','Appearance'],['sizing','Text & icons'],['workspace','Workspace'],['shapes','Card shapes'],['library-tools','Library tools']])nav.append(button(label,()=>{const section=document.getElementById(`settings-${id}`);section.scrollIntoView({block:'start',behavior:prefs.reduceMotion?'instant':'smooth'});section.tabIndex=-1;section.focus({preventScroll:true})}));
nav.append(el('div',{class:'settings-nav-links'},el('a',{href:'manual.html',target:'_blank'},'How it works ↗'),el('a',{href:'terms.html',target:'_blank'},'Terms & conditions ↗'),el('a',{href:'privacy.html',target:'_blank'},'Privacy ↗')));
page.append(el('header',{class:'settings-header'},button([glyph('undo'),'Back to library'],showLibrary,{class:'secondary'}),el('div',{},el('h1',{id:'settings-title',tabindex:-1},'Settings'),el('p',{},'Your workspace, your way.'))),el('div',{class:'settings-layout'},nav,form));app.append(page);syncSettings();return page;}
function showPage(open,focus=true){if(open&&!settingsOpen)libraryScroll=scrollY;settingsOpen=open;let page=document.getElementById('settings-page');if(open&&!page)page=buildSettingsPage();document.getElementById('library-page').hidden=open;if(page)page.hidden=!open;document.documentElement.dataset.page=open?'settings':'library';document.title=open?'Settings · 1stTab':initialTitle;if(open)syncSettings();window.scrollTo(0,open?0:libraryScroll);if(focus)(open?document.getElementById('settings-title'):document.querySelector('.settings-button')).focus({preventScroll:true});}
function openSettings(){if(!isSettingsRoute())history.pushState({page:'settings'},'',preview?'#settings':chrome.runtime.getURL('settings.html'));showPage(true);}
function showLibrary(){if(isSettingsRoute())history.pushState({page:'library'},'',libraryURL);showPage(false);}
window.addEventListener('popstate',()=>{if(state)showPage(isSettingsRoute())});
function sidebarMax(){return Math.max(220,Math.min(520,Math.round(innerWidth*.45)))}
function syncResizeHandle(){const handle=document.getElementById('sidebar-resizer');if(!handle)return;handle.setAttribute('aria-valuemax',String(sidebarMax()));handle.setAttribute('aria-valuenow',String(Math.min(prefs.sidebarWidth,sidebarMax())));handle.setAttribute('aria-valuetext',`${Math.min(prefs.sidebarWidth,sidebarMax())} pixels`);}
function resizeHandle(){const handle=el('div',{id:'sidebar-resizer',class:'sidebar-resizer',role:'separator',tabindex:0,'aria-label':'Resize folder sidebar','aria-orientation':'vertical','aria-controls':'folders','aria-valuemin':220,title:'Drag to resize · Arrow keys to adjust · Double-click to reset'});let drag=null;
const paint=width=>document.documentElement.style.setProperty('--sidebar-width',`${width}px`);
handle.addEventListener('pointerdown',e=>{if(e.button!==0)return;e.preventDefault();drag={x:e.clientX,width:document.getElementById('folders').getBoundingClientRect().width,value:prefs.sidebarWidth};handle.setPointerCapture(e.pointerId);document.body.classList.add('resizing-sidebar')});
handle.addEventListener('pointermove',e=>{if(!drag)return;drag.value=Math.round(Math.max(220,Math.min(sidebarMax(),drag.width+e.clientX-drag.x)));paint(drag.value);handle.setAttribute('aria-valuenow',String(drag.value))});
const finish=commit=>{if(!drag)return;const width=drag.value;drag=null;document.body.classList.remove('resizing-sidebar');if(commit)run(()=>changePreference({sidebarWidth:width}));else{paint(prefs.sidebarWidth);syncResizeHandle()}};
handle.addEventListener('pointerup',()=>finish(true));handle.addEventListener('pointercancel',()=>finish(false));handle.addEventListener('lostpointercapture',()=>finish(false));
handle.addEventListener('dblclick',()=>run(()=>changePreference({sidebarWidth:270})));
handle.addEventListener('keydown',e=>{const step=e.shiftKey?50:10;const width=Math.min(prefs.sidebarWidth,sidebarMax());const values={ArrowLeft:width-step,ArrowRight:width+step,Home:220,End:sidebarMax()};if(!(e.key in values))return;e.preventDefault();run(()=>changePreference({sidebarWidth:Math.max(220,Math.min(sidebarMax(),values[e.key]))}))});window.addEventListener('resize',syncResizeHandle);return handle;}
function finishDrag(){dragIds=[];document.body.classList.remove('is-dragging');for(const n of document.querySelectorAll('.dragging,.drop-before,.drop-after,.drop-folder'))n.classList.remove('dragging','drop-before','drop-after','drop-folder');}
function bindFolderDrop(node,id){node.addEventListener('dragover',e=>{if(!dragIds.length||state?.nodes.get(id)?.managed)return;e.preventDefault();e.dataTransfer.dropEffect='move';node.classList.add('drop-folder')});node.addEventListener('dragleave',()=>node.classList.remove('drop-folder'));node.addEventListener('drop',e=>{if(!dragIds.length)return;e.preventDefault();const ids=[...dragIds];finishDrag();run(async()=>{const current=await lib.load();lib.destination(current,id);const moving=ids.filter(i=>current.nodes.get(i)?.parentId!==id);if(!moving.length){message('These bookmarks are already in this collection.');return}await tracked('Move bookmarks',()=>lib.move(moving,id));selected.clear();await refresh();message(`Moved ${moving.length} bookmark${moving.length===1?'':'s'} to ${current.nodes.get(id).title}. Undo available.`);});});}
function renderTabs(){const tabs=document.querySelector('#collection-tabs');tabs.replaceChildren();const add=(text,id='',favorites=false,icon='folder')=>{const active=filter.folder===id&&filter.favorites===favorites;const b=button([glyph(icon),text],()=>chooseCollection(id,favorites),{class:'collection-tab'+(active?' active':''),'aria-pressed':active});if(id)bindFolderDrop(b,id);tabs.append(b)};add('All bookmarks','',false,'grid');add('Favorites','',true,'star');const candidates=state.folders.filter(f=>f.parentId&&!f.managed&&(f.children?.length||0)>0);for(const f of candidates.slice(0,4))add(f.title||'Untitled',f.id);}
function renderFolders(){if(!state)return;renderTabs();const n=document.querySelector('#folders');const shown=narrow.matches?mobileTreeOpen:treeOpen;n.hidden=!shown;document.querySelector('#tree-scrim').hidden=!narrow.matches||!mobileTreeOpen;document.querySelector('#workspace-layout').classList.toggle('tree-hidden',!shown);document.querySelector('#tree-toggle').setAttribute('aria-expanded',String(shown));n.replaceChildren(el('a',{class:'sidebar-brand',href:chrome.runtime.getURL('manager.html'),'aria-label':brandName},el('span',{class:'brand-symbol'},glyph('bookmark')),el('span',{},'1st',el('b',{},'Tab'),versionTag())),iconButton('Close collections','close',()=>{mobileTreeOpen=false;renderFolders()},{class:'icon-button mobile-close'}));
const shortcut=(label,icon,favorites)=>button([glyph(icon),el('span',{class:'tree-label'},label),el('span',{class:'tree-count'},String(favorites?state.bookmarks.filter(b=>normalizeMeta(state.metadata[b.id]).pinned).length:state.bookmarks.length))],()=>chooseCollection('',favorites),{class:'tree-node shortcut'+(!filter.folder&&filter.favorites===favorites?' selected':''),'aria-pressed':!filter.folder&&filter.favorites===favorites});n.append(shortcut('All bookmarks','grid',false),shortcut('Favorites','star',true),el('div',{class:'tree-divider'}));
function count(nodes){return nodes.reduce((sum,v)=>sum+(v.url?1:count(v.children||[])),0)}
function walk(nodes,container){for(const f of nodes){if(f.url)continue;if(!f.parentId){walk(f.children||[],container);continue}const branches=(f.children||[]).filter(x=>!x.url);const isOpen=!collapsed.has(f.id);let editable=true;try{lib.editable(state,f.id)}catch{editable=false}const toggle=iconButton(`${isOpen?'Collapse':'Expand'} ${f.title}`,'chevron',async()=>{if(isOpen)collapsed.add(f.id);else collapsed.delete(f.id);renderFolders();await savePrefs();},{class:'tree-toggle'+(!branches.length?' placeholder':''),'aria-expanded':isOpen,disabled:!branches.length});const b=button([glyph(f.managed?'lock':'folder'),el('span',{class:'tree-label'},f.title||'Untitled collection'),el('span',{class:'tree-count'},String(count(f.children||[])))],()=>chooseCollection(f.id,false),{class:'tree-node'+(filter.folder===f.id?' selected':''),'aria-pressed':filter.folder===f.id,'aria-label':`${f.title}, folder`,'data-folder-id':f.id});if(!f.managed)bindFolderDrop(b,f.id);const actions=el('div',{class:'tree-actions'},iconButton(`Add collection in ${f.title}`,'plus',()=>editFolder(null,f.id),{disabled:f.managed}),iconButton(`Edit folder ${f.title}`,'edit',()=>editFolder(f),{disabled:!editable}),iconButton(`Delete folder ${f.title}`,'trash',()=>previewDelete([f.id]),{disabled:!editable,class:'icon-button danger'}));const group=el('div',{class:'tree-group'},el('div',{class:'tree-line'},toggle,b,actions));if(branches.length&&isOpen){const children=el('div',{class:'tree-children'});walk(branches,children);group.append(children)}container.append(group)}}walk(state.tree,n);
const chooser=document.querySelector('#folder-filter');chooser.replaceChildren(el('option',{value:''},'All collections'),state.folders.filter(f=>f.parentId).map(f=>el('option',{value:f.id},f.title||'Untitled collection')));chooser.value=filter.folder;
}
function visibleBookmarks(){const hits=searchBookmarks(state.tree,state.metadata,filter);if(sortMode==='title')hits.sort((a,b)=>a.title.localeCompare(b.title));if(sortMode==='newest')hits.sort((a,b)=>(b.dateAdded||0)-(a.dateAdded||0));return hits;}
function tileColor(id){let hash=0;for(const c of id)hash=(hash*31+c.codePointAt(0))>>>0;return hash%6;}
function tagSelected(){const ids=[...selected];modal(`Tag ${ids.length} bookmarks`,(dialog,form)=>{const tags=el('input',{required:true,placeholder:'research, ideas',maxlength:2400});form.append(field('Tags, separated by commas',tags),el('p',{},'Adds these tags to every selected bookmark. Existing tags and notes are preserved.'));return button('Add tags',async()=>{if(!form.reportValidity())return;const added=normalizeMeta({tags:tags.value.split(',')}).tags;if(!added.length)throw Error('Enter at least one tag.');await tracked('Tag bookmarks',async()=>{for(const id of ids){const fresh=await lib.load();await lib.setMeta(id,{...normalizeMeta(fresh.metadata[id]),tags:[...new Set([...normalizeMeta(fresh.metadata[id]).tags,...added])]});}});dialog.close();await refresh();message(`Tags added to ${ids.length} bookmarks. Undo available.`);},{class:'primary'})});}
function renderResults(){if(!state)return;syncFilters();const hits=visibleBookmarks();document.querySelector('#workspace-title').textContent=filter.folder?(state.nodes.get(filter.folder)?.title||'Collection'):filter.favorites?'Favorites':'All bookmarks';document.querySelector('#count').textContent=`${hits.length} bookmark${hits.length===1?'':'s'} · ${state.folders.filter(f=>f.parentId).length} collections`;document.querySelector('#total-count').textContent=`${state.bookmarks.length} saved places`;
document.querySelector('#selection-toolbar').hidden=!selected.size;document.querySelector('#selection-count').textContent=`${selected.size} selected`;for(const name of['move-selected','delete-selected','clear-selected','tag-selected'])document.getElementById(name).disabled=!selected.size;document.querySelector('#sort-order').value=sortMode;for(const name of['list','grid'])document.getElementById(`view-${name}`).setAttribute('aria-pressed',String(mode===name));renderTabs();
const results=document.querySelector('#results');results.className='results '+mode;results.replaceChildren();const frag=document.createDocumentFragment();for(const b of hits.slice(0,limit)){const m=normalizeMeta(state.metadata[b.id]);let url,host=b.url;try{url=safeUrl(b.url);host=new URL(url).hostname.replace(/^www\./,'')}catch{url=null}const pick=el('input',{type:'checkbox',checked:selected.has(b.id),'aria-label':`Select ${b.title}`,disabled:b.managed,onchange:e=>{if(e.target.checked)selected.add(b.id);else selected.delete(b.id);renderResults()}});const link=url?el('a',{href:url,target:'_blank',rel:'noopener noreferrer',title:b.title||b.url},b.title||b.url):el('span',{},b.title||b.url);const icon=el('div',{class:`bookmark-tile tone-${tileColor(b.id)}`,'aria-hidden':'true'},m.initial||Array.from(b.title||host)[0]?.toUpperCase()||'B');if(m.color&&CSS.supports('color',m.color))icon.style.backgroundColor=m.color;
const tagList=el('div',{class:'bookmark-tags'},m.tags.slice(0,3).map(t=>button(t,async()=>{filter.tag=t;document.querySelector('#tag-filter').value=t;await changePreference({filtersOpen:true})},{class:'tag'})));const collectionName=state.nodes.get(b.parentId)?.title||'Collection';const info=el('div',{class:'bookmark-body'},el('div',{class:'bookmark-title'},link),el('p',{class:'bookmark-note',title:m.note||host},m.note||host),tagList);const meta=el('div',{class:'bookmark-meta'},el('span',{class:'bookmark-host',title:host},host),button([glyph('folder'),el('span',{},collectionName)],()=>chooseCollection(b.parentId,false),{class:'folder-chip',title:collectionName}));const actions=el('div',{class:'row-actions'},iconButton('Edit','edit',()=>editBookmark(b),{disabled:b.managed}),iconButton('Delete','trash',()=>previewDelete([b.id]),{disabled:b.managed,class:'icon-button danger'}));const pin=iconButton(m.pinned?'Remove favorite':'Add favorite','star',async()=>{await tracked('Toggle favorite',()=>lib.setMeta(b.id,{...m,pinned:!m.pinned}));await refresh();},{disabled:b.managed,class:'icon-button favorite'+(m.pinned?' pinned':'')});const card=el('article',{class:'bookmark'+(selected.has(b.id)?' selected':''),draggable:!b.managed,'data-bookmark-id':b.id,'aria-label':`${b.title} bookmark`},el('div',{class:'bookmark-top'},icon,el('div',{class:'card-controls'},b.managed?el('span',{class:'managed-label',title:'Managed bookmark'},glyph('lock')):el('span',{class:'drag-handle',title:'Drag to move or sort'},glyph('drag')),pin,pick)),info,meta,actions);
card.addEventListener('dragstart',e=>{if(e.target.closest('button,input,a')||b.managed){e.preventDefault();return}dragIds=selected.has(b.id)?state.bookmarks.filter(x=>selected.has(x.id)&&!x.managed).map(x=>x.id):[b.id];e.dataTransfer.effectAllowed='move';e.dataTransfer.setData('text/plain',dragIds.join(','));card.classList.add('dragging');document.body.classList.add('is-dragging');message(`Dragging ${dragIds.length} bookmark${dragIds.length===1?'':'s'} · Drop on a collection to move, or between bookmarks in the same folder to sort.`)});card.addEventListener('dragend',finishDrag);
const after=e=>{const r=card.getBoundingClientRect();return mode==='list'?e.clientY>r.top+r.height/2:e.clientX>r.left+r.width/2};card.addEventListener('dragover',e=>{if(!dragIds.length||dragIds.includes(b.id)||b.managed)return;e.preventDefault();e.dataTransfer.dropEffect='move';document.querySelectorAll('.drop-before,.drop-after').forEach(n=>n.classList.remove('drop-before','drop-after'));card.classList.add(after(e)?'drop-after':'drop-before')});card.addEventListener('dragleave',()=>card.classList.remove('drop-before','drop-after'));card.addEventListener('drop',e=>{if(!dragIds.length)return;e.preventDefault();const ids=[...dragIds],position=after(e);finishDrag();run(async()=>{await tracked('Sort bookmarks',()=>lib.reorder(ids,b.id,position));sortMode='manual';await savePrefs();await refresh();message('Bookmark order updated. Undo available.');})});frag.append(card)}results.append(frag);
if(!hits.length)results.append(el('div',{class:'empty'},el('div',{class:'empty-symbol'},glyph(filter.query?'search':'folder')),el('h2',{},state.bookmarks.length?'Nothing here yet':'A home for your next discovery'),el('p',{},state.bookmarks.length?'Try another collection or clear your filters. You can also drag bookmarks into an empty collection.':'Save your first bookmark or import your existing library.'),button('Add bookmark',()=>editBookmark(),{class:'primary'})));const more=document.querySelector('#more');more.hidden=hits.length<=limit;more.textContent=`Show more (${Math.max(0,hits.length-limit)} remaining)`;
}
function libraryToolsSection(dialog){const form=el('section',{class:'settings-section',id:'settings-library-tools','aria-labelledby':'settings-library-title'},el('div',{class:'settings-section-title'},glyph('folder'),el('h3',{id:'settings-library-title'},'Library tools')));const importInput=el('input',{type:'file',accept:'.json,application/json',hidden:true,onchange:e=>run(async()=>{const f=e.target.files[0];if(!f)return;if(f.size>20_000_000)throw Error('Import is limited to 20 MB.');const doc=parseImport(await f.text());dialog.close();previewImport(doc)})});form.append(el('p',{},'Your bookmarks follow Chrome’s sync settings. Tags and notes stay on this device.'),el('div',{class:'tool-grid'},button([glyph('export'),'Export library'],()=>exportFile(makeExport(state),'1sttab-bookmarks.json')),button([glyph('import'),'Import export'],()=>importInput.click()),button([glyph('undo'),'Undo last edit'],async()=>{await undoOperation(lib);await refresh();message('Last supported operation undone.');dialog.close()}),button([glyph('history'),'Restore snapshot'],()=>{dialog.close();return restoreSnapshot()}),button([glyph('cleanup'),'Review cleanup'],()=>{dialog.close();cleanup()})),importInput);if(chrome.runtime.getManifest?.().optional_host_permissions?.length)form.append(optionalTools());form.append(el('p',{class:'tool-links'},el('a',{href:'manual.html',target:'_blank'},'User guide'),el('a',{href:'privacy.html',target:'_blank'},'Privacy'),el('a',{href:'terms.html',target:'_blank'},'Terms & conditions')));return form;}
function build(){app.replaceChildren();const search=el('input',{type:'search',id:'search',placeholder:'Find a bookmark, idea, or saved place…','aria-label':'Search bookmarks',oninput:e=>{filter.query=e.target.value;limit=100;renderResults()}});const searchRow=el('div',{class:'search-row'},el('a',{class:'wordmark',href:chrome.runtime.getURL('manager.html'),'aria-label':brandName},el('span',{class:'brand-symbol'},glyph('bookmark')),el('span',{},'1st',el('b',{},'Tab'),versionTag())),el('label',{class:'search-box'},glyph('search'),search,el('kbd',{},'⌘ / Ctrl K')),el('span',{id:'total-count',class:'total-count'}),iconButton('Settings','settings',openSettings,{class:'icon-button settings-button'}));
const toggleFilters=()=>changePreference({filtersOpen:!prefs.filtersOpen});const tools=el('div',{class:'workspace-tools'},iconButton('Collections','sidebar',async()=>{if(narrow.matches)mobileTreeOpen=!mobileTreeOpen;else treeOpen=!treeOpen;renderFolders();await savePrefs()},{id:'tree-toggle','aria-expanded':true,'aria-controls':'folders'}),button([glyph('sliders'),el('span',{id:'filters-toggle-label'},'Show filters'),el('span',{id:'filters-active-count',class:'filter-count','aria-hidden':'true',hidden:true})],toggleFilters,{id:'filters-toggle',class:'filters-toggle','aria-label':'Show filters','aria-expanded':false,'aria-controls':'filter-tray','aria-describedby':'filters-summary',title:'Show filters'}),iconButton('Light / dark','moon',async()=>{await changePreference({theme:document.documentElement.dataset.theme==='dark'?'light':'dark'})}),el('div',{class:'view-switch','aria-label':'Bookmark view'},iconButton('List view','list',async()=>{mode='list';renderResults();await savePrefs()},{id:'view-list','aria-pressed':false}),iconButton('Grid view','grid',async()=>{mode='grid';renderResults();await savePrefs()},{id:'view-grid','aria-pressed':true})),el('select',{id:'sort-order','aria-label':'Sort bookmarks',onchange:e=>run(async()=>{sortMode=e.target.value;renderResults();await savePrefs()})},el('option',{value:'manual'},'Manual order'),el('option',{value:'title'},'Name A–Z'),el('option',{value:'newest'},'Newest first')),button([glyph('plus'),'New collection'],()=>editFolder(),{class:'secondary'}),button([glyph('plus'),'Add bookmark'],()=>editBookmark(),{class:'primary'}));
const toolbar=el('div',{class:'workspace-toolbar'},el('div',{class:'workspace-heading'},el('h1',{id:'workspace-title'},'All bookmarks'),el('span',{id:'count',class:'workspace-count','aria-live':'polite'})),tools);
const folder=el('select',{id:'folder-filter','aria-label':'Filter folder',onchange:e=>{filter.folder=e.target.value;limit=100;renderResults();renderFolders()}}),tag=el('input',{id:'tag-filter',placeholder:'Filter by tag','aria-label':'Filter by tag',oninput:e=>{filter.tag=e.target.value;renderResults()}}),domain=el('input',{placeholder:'Filter by domain','aria-label':'Filter by domain',oninput:e=>{filter.domain=e.target.value;renderResults()}}),favorites=el('input',{type:'checkbox',id:'favorites-filter',onchange:e=>{filter.favorites=e.target.checked;renderResults();renderFolders()}});const filters=el('div',{id:'filter-tray',class:'filter-tray',hidden:!prefs.filtersOpen,role:'region','aria-label':'Bookmark filters'},field('Collection',folder),field('Tag',tag),field('Domain',domain),field('Favorites',favorites),button('Reset filters',()=>{filter={query:'',folder:'',tag:'',domain:'',favorites:false};search.value='';tag.value='';domain.value='';favorites.checked=false;renderResults();renderFolders()}));
const layout=el('div',{class:'workspace-layout',id:'workspace-layout'},button('',()=>{mobileTreeOpen=false;renderFolders()},{id:'tree-scrim',class:'tree-scrim',hidden:true,'aria-label':'Close collections drawer'}),el('aside',{class:'tree','aria-label':'Bookmark folders',id:'folders'}),resizeHandle(),el('section',{'aria-label':'Saved bookmarks',class:'bookmark-workspace'},el('div',{id:'results'}),button('Show more',()=>{limit+=100;renderResults()},{id:'more'})));
const selection=el('div',{id:'selection-toolbar',class:'selection-toolbar',hidden:true},el('span',{id:'selection-count','aria-live':'polite'}),button([glyph('folder'),'Move selected'],()=>previewMove([...selected]),{id:'move-selected'}),button([glyph('tag'),'Tag selected'],tagSelected,{id:'tag-selected'}),button([glyph('trash'),'Delete selected'],()=>previewDelete([...selected]),{id:'delete-selected',class:'danger'}),iconButton('Clear','close',()=>{selected.clear();renderResults()},{id:'clear-selected'}));app.append(el('div',{id:'library-page'},el('div',{class:'workspace-shell'},searchRow,el('nav',{id:'collection-tabs',class:'collection-tabs','aria-label':'Collections'}),toolbar,filters,layout),selection),el('p',{id:'status',role:'status','aria-live':'polite',class:'sr-only'},'Loading library…'),el('span',{id:'filters-summary',class:'sr-only'}));syncFilters();syncResizeHandle();document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();if(settingsOpen)showLibrary();search.focus()}if(e.key==='Escape'){finishDrag();mobileTreeOpen=false;if(state)renderFolders()}});}

function optionalTools(){return el('details',{},el('summary',{},'Optional AI organization and Google Drive backup'),el('p',{},'These tools are disabled until you grant access. Review recipients and data before each operation. The local library works without them.'),el('div',{class:'toolbar'},button('Review AI organization',aiDialog),button('Disable AI access',async()=>{await disableAI(chrome);message('AI access removed.');}),button('Review cloud backup',driveDialog),button('Disconnect Google Drive',async()=>{await disableDrive(chrome);message('Cached Google tokens and extension access removed. Existing backups remain in Drive until deleted.');})));}
function aiDialog(){const ids=[...selected];if(!ids.length||ids.length>100)throw Error('Select 1–100 bookmarks first.');modal('Review data sent to OpenAI',(dialog,form)=>{const key=el('input',{type:'password',required:true,autocomplete:'off'}),model=el('input',{required:true,placeholder:'Your model ID'}),query=el('input',{maxlength:1000,placeholder:'Optional: find research about…'});form.append(el('p',{},'OpenAI receives only the selected bookmark IDs, titles and URLs, plus destination folder IDs/names and your optional find query. Notes, API keys in stored data and unselected links are excluded. The API key authorizes the request and is kept in this dialog only. Provider charges and retention policies apply.'),el('ul',{},ids.map(id=>el('li',{},state.nodes.get(id)?.url||id))),field('Your OpenAI API key',key),field('Model ID',model),field('Find within selected bookmarks (optional)',query));return button('Grant access and request suggestions',async()=>{if(!form.reportValidity())return;await enableAI(chrome);const output=await suggestBookmarks(chrome,{apiKey:key.value,model:model.value,query:query.value,bookmarks:ids.map(id=>state.nodes.get(id)).filter(Boolean),folders:writableFolders()});key.value='';dialog.close();aiPreview(output,Boolean(query.value.trim()));},{class:'primary'});});}
function aiPreview(suggestions,retrieval=false){modal(retrieval?'Matching saved bookmarks':'Review AI suggestions before applying',(dialog,form)=>{if(retrieval){for(const v of suggestions){const b=state.nodes.get(v.id);if(b)form.append(el('p',{},el('a',{href:safeUrl(b.url),target:'_blank',rel:'noopener noreferrer'},b.title||b.url)),el('p',{},v.reason));}if(!suggestions.length)form.append(el('p',{},'No matches returned.'));return button('Close',()=>dialog.close());}const chosen=new Set();if(!suggestions.length)form.append(el('p',{},'No valid suggestions returned.'));for(const v of suggestions){const check=el('input',{type:'checkbox',onchange:e=>e.target.checked?chosen.add(v):chosen.delete(v)});form.append(field(`${state.nodes.get(v.id)?.title}: tags ${v.tags.join(', ')||'(none)'}; folder ${state.nodes.get(v.folderId)?.title||'(keep current)'}`,check),el('p',{},v.reason))}return button('Apply selected suggestions',async()=>{if(!chosen.size)throw Error('Select suggestions to apply.');await tracked('AI organization',async()=>{for(const v of chosen){const fresh=await lib.load();lib.editable(fresh,v.id);const m=normalizeMeta(fresh.metadata[v.id]);if(v.folderId)await lib.move([v.id],v.folderId);await lib.setMeta(v.id,{...m,tags:[...new Set([...m.tags,...v.tags])]});}});dialog.close();await refresh();message('Selected suggestions applied.');},{class:'primary'});});}
function driveDialog(){modal('Review Google Drive backup',(dialog,form)=>{form.append(el('p',{},'Google receives a bookmark export including URLs, tags and notes. Backups use the private appDataFolder with drive.appdata access. No calendar/tasks permissions, automatic upload or account email access. Backups remain until you delete them. Restore is additive with a preview; it may create duplicates.'),el('p',{},'Google sign-in requires the publisher’s OAuth client to be configured for this extension ID.'));const actions=el('div',{class:'toolbar'},button('Connect and upload this library',async()=>{await enableDrive(chrome);const backup=await uploadBackup(chrome,await lib.load());dialog.close();message(`Backup uploaded: ${backup.name||backup.id}`);}),button('Connect and review backups',async()=>{await enableDrive(chrome);const backups=await listBackups(chrome);dialog.close();driveList(backups);}));return actions;});}
function driveList(backups){modal('Google Drive backups',(dialog,form)=>{if(!backups.length)form.append(el('p',{},'No backups found.'));for(const b of backups)form.append(el('article',{},el('p',{},`${b.name} — ${b.createdTime||''}`),button('Preview restore',async()=>{const doc=await downloadBackup(chrome,b.id);dialog.close();previewImport(doc);}),button('Delete backup',()=>{modal('Delete this cloud backup?',(d,f)=>{f.append(el('p',{},b.name));return button('Confirm cloud deletion',async()=>{await deleteBackup(chrome,b.id);d.close();dialog.close();message('Cloud backup deleted.');},{class:'danger'});});})));return button('Close',()=>dialog.close());});}

async function start(){await lib.migrate();applyPrefs((await chrome.storage.local.get('bookmarks.preferences.v1'))['bookmarks.preferences.v1']||{});build();await refresh();message('Library ready.');lib.subscribe(()=>run(refresh));
const capture=(await chrome.storage.local.get('bookmarks.capture.v1'))['bookmarks.capture.v1'];if(capture&&Date.now()-capture.createdAt<300000){await chrome.storage.local.remove('bookmarks.capture.v1');editBookmark(null,capture)}chrome.storage.onChanged.addListener((changes,area)=>{if(area==='local'&&changes['bookmarks.preferences.v1'])applyPrefs(changes['bookmarks.preferences.v1'].newValue||{});});if(isSettingsRoute())showPage(true,false);}
systemDark.addEventListener('change',()=>{if(prefs.theme==='system')applyAppearance()});
narrow.addEventListener('change',()=>{mobileTreeOpen=false;if(state)renderFolders()});
run(start);
