import {chromium, browserOptions} from './browser-runtime.mjs';
import {readFile} from 'node:fs/promises';import {createServer}from'node:http';import {resolve,extname}from'node:path';import assert from'node:assert/strict';
const root=resolve('.');const server=createServer(async(req,res)=>{try{const path=resolve(root,'.'+new URL(req.url,'http://localhost').pathname);if(!path.startsWith(root+'/'))throw Error('bad path');const body=await readFile(path);res.setHeader('Content-Type',({'.js':'text/javascript','.html':'text/html','.css':'text/css','.png':'image/png'})[extname(path)]||'text/plain');res.end(body)}catch{res.statusCode=404;res.end()}});await new Promise(r=>server.listen(0,'127.0.0.1',r));
const origin=`http://127.0.0.1:${server.address().port}`,requests=[],errors=[];let browser;
try{
browser=await chromium.launch(browserOptions);
const ctx=await browser.newContext();const mock=(await readFile('tests/mock-chrome.js','utf8')).replace('export function mockChrome','function mockChrome');await ctx.addInitScript({content:mock+`;window.chrome=mockChrome();chrome.runtime={getURL:p=>location.origin+'/'+p,getManifest:()=>({})};chrome.tabs={create:async v=>v};`});
const page=await ctx.newPage();page.setDefaultTimeout(8000);page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>requests.push(r.url()));await page.goto(origin+'/manager.html');await page.getByText('Library ready.',{exact:true}).waitFor();assert.equal(await page.locator('.bookmark').count(),3);
assert.equal(await page.getByRole('button',{name:'List view',exact:true}).getAttribute('aria-pressed'),'true');await page.getByRole('button',{name:'Collections',exact:true}).click();assert.equal(await page.locator('#folders').isVisible(),false);await page.getByRole('button',{name:'Collections',exact:true}).click();const collapse=page.getByRole('button',{name:'Collapse Bookmarks bar',exact:true});assert.equal(await collapse.getAttribute('aria-expanded'),'true');await collapse.click();assert.equal(await page.getByRole('button',{name:'Expand Bookmarks bar',exact:true}).getAttribute('aria-expanded'),'false');await page.getByRole('button',{name:'Expand Bookmarks bar',exact:true}).click();
await page.getByRole('button',{name:'Add bookmark',exact:true}).click();const dialog=page.getByRole('dialog');await dialog.getByLabel('Title',{exact:true}).fill('My saved page');await dialog.getByLabel('URL',{exact:true}).fill('https://saved.example');await dialog.getByLabel('Tags, separated by commas').fill('work');await dialog.getByRole('button',{name:'Save',exact:true}).click();await page.getByText('Bookmark saved.',{exact:true}).waitFor();assert.equal(await page.locator('.bookmark').count(),4);
await page.getByRole('searchbox').fill('my saved');assert.equal(await page.locator('.bookmark').count(),1);await page.getByRole('searchbox').fill('');await page.locator('#filters-toggle').click();await page.getByLabel('Filter by domain').fill('example.com');assert.equal(await page.locator('.bookmark').count(),1);await page.getByLabel('Filter by domain').fill('');
await page.getByLabel('Select My saved page',{exact:true}).check();await page.getByRole('button',{name:'Move selected',exact:true}).click();await page.getByRole('dialog').getByLabel('Destination').selectOption('other');await page.getByRole('dialog').getByRole('button',{name:'Confirm move'}).click();await page.getByText('Items moved. Recovery snapshot retained.',{exact:true}).waitFor();
await page.getByLabel('Select My saved page',{exact:true}).check();await page.getByRole('button',{name:'Delete selected',exact:true}).click();await page.getByRole('dialog').getByRole('button',{name:'Cancel',exact:true}).click();assert.equal(await page.locator('.bookmark').count(),4);
await page.getByRole('button',{name:'Tag selected',exact:true}).click();await page.getByRole('dialog').getByLabel('Tags, separated by commas').fill('ideas');await page.getByRole('dialog').getByRole('button',{name:'Add tags',exact:true}).click();await page.getByText('Tags added to 1 bookmarks. Undo available.',{exact:true}).waitFor();assert.ok(await page.getByText('ideas',{exact:true}).count());await page.getByRole('button',{name:'Clear',exact:true}).click();assert.equal(await page.locator('#selection-toolbar').isVisible(),false);
const bookmark=name=>page.getByRole('article',{name:name+' bookmark',exact:true});const target=page.locator('#folders [data-folder-id="folder"]');await bookmark('My saved page').locator('.drag-handle').dragTo(target);await page.getByText('Moved 1 bookmark to Work. Undo available.',{exact:true}).waitFor();await target.click();assert.equal(await page.locator('.bookmark').count(),2);await page.getByRole('button',{name:'List view',exact:true}).click();await bookmark('My saved page').locator('.drag-handle').dragTo(bookmark('Other'),{targetPosition:{x:100,y:5}});await page.getByText('Bookmark order updated. Undo available.',{exact:true}).waitFor();assert.equal(await page.locator('.bookmark-title a').first().innerText(),'My saved page');await page.getByRole('button',{name:'Settings',exact:true}).click();await page.locator('#settings-page').getByRole('button',{name:'Undo last edit',exact:true}).click();await page.getByText('Last supported operation undone.',{exact:true}).waitFor();assert.equal(await page.locator('.bookmark-title a').first().innerText(),'Other');await page.locator('#folders .shortcut').filter({hasText:'All bookmarks'}).click();
await page.setViewportSize({width:390,height:844});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));await page.getByRole('button',{name:'Grid view',exact:true}).click();assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));await page.getByRole('button',{name:'List view',exact:true}).click();await page.screenshot({path:'tests/library-mobile.png',fullPage:true,animations:'disabled'});
await page.goto(origin+'/panel.html');await page.getByText('Library ready.',{exact:true}).waitFor();await page.locator('#filters-toggle').click();await page.keyboard.press('Control+k');assert.equal(await page.locator('#search').evaluate(n=>n===document.activeElement),true);await page.setViewportSize({width:1280,height:900});await page.screenshot({path:'tests/library-desktop.png',fullPage:true,animations:'disabled'});
await page.getByRole('button',{name:'Light / dark',exact:true}).click();assert.equal(await page.locator('html').getAttribute('data-theme'),'dark');assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));await page.screenshot({path:'tests/library-dark.png',fullPage:true,animations:'disabled'});await page.getByRole('button',{name:'Light / dark',exact:true}).click();assert.deepEqual(errors,[]);assert.ok(requests.every(u=>u.startsWith(origin)));console.log('Browser checks passed: capture form, search/filter, move preview, delete cancellation, panel, keyboard focus, mobile overflow, no remote requests.');
}finally{await browser?.close();await new Promise(r=>server.close(r));}
