import test from'node:test';import assert from'node:assert/strict';import{enableAI,suggestBookmarks,enableDrive,uploadBackup,downloadBackup,disableDrive}from'../bookmark-core/integrations.js';import{mockChrome}from'./mock-chrome.js';import{BookmarkLibrary}from'../bookmark-core/library.js';
const request={apiKey:'secret',model:'user-model',bookmarks:[{id:'a',title:'Link',url:'https://example.com',note:'private'}],folders:[{id:'bar',title:'Library'}]};
test('permission denial makes no service request',async()=>{const api={permissions:{request:async()=>false,contains:async()=>false}};await assert.rejects(enableAI(api),/declined/);await assert.rejects(enableDrive(api),/declined/);let calls=0;await assert.rejects(suggestBookmarks(api,request,async()=>calls++),/Enable/);assert.equal(calls,0)});
test('AI payload contains only selected title/URL and validates returned IDs and folders',async()=>{let body;const api={permissions:{contains:async()=>true}};const suggestions=await suggestBookmarks(api,request,async(url,opts)=>{body=JSON.parse(opts.body);return{ok:true,json:async()=>({choices:[{message:{content:JSON.stringify({suggestions:[{id:'unknown',tags:['bad']},{id:'a',tags:['work'],folderId:'unknown',reason:'Reason'}]})}}]})}});assert.equal(suggestions.length,1);assert.equal(suggestions[0].folderId,null);assert.ok(!optsLeak(body,'secret'));assert.ok(!JSON.stringify(body).includes('private'))});
function optsLeak(body,s){return JSON.stringify(body).includes(s)}
test('AI failures and malformed output apply no changes',async()=>{const api={permissions:{contains:async()=>true}};await assert.rejects(suggestBookmarks(api,request,async()=>({ok:false,status:401})),/401/);await assert.rejects(suggestBookmarks(api,request,async()=>({ok:true,json:async()=>({choices:[{message:{content:'bad'}}]})})),/invalid JSON/)});
test('Drive backup excludes secrets and uses only appDataFolder; download is validated',async()=>{const api=mockChrome();api.permissions={contains:async()=>true,remove:async()=>true};api.identity={getAuthToken:async()=>({token:'private-token'}),clearAllCachedAuthTokens:async()=>{}};api.local['key']='private-key';const s=await new BookmarkLibrary(api).load();let body;await uploadBackup(api,s,async(url,opts)=>{body=opts.body;return{ok:true,json:async()=>({id:'backup'})}});assert.ok(body.includes('appDataFolder'));assert.ok(!body.includes('private-key'));assert.ok(!body.includes('private-token'));await assert.rejects(downloadBackup(api,'bad/id'),/Invalid/);await assert.rejects(downloadBackup(api,'valid',async()=>({ok:true,text:async()=>'{}'})),/version 1/);await disableDrive(api)});

test('AI retrieval never returns mutation fields',async()=>{const api={permissions:{contains:async()=>true}};const result=await suggestBookmarks(api,{...request,query:'Find research'},async()=>({ok:true,json:async()=>({choices:[{message:{content:JSON.stringify({suggestions:[{id:'a',tags:['injected'],folderId:'bar',reason:'Matches'}]})}}]})}));assert.deepEqual(result[0].tags,[]);assert.equal(result[0].folderId,null)});
