export function mockChrome() {
  let next=100; let roots=[{id:'root', title:'', children:[{id:'bar',parentId:'root',title:'Bookmarks bar',children:[{id:'a',parentId:'bar',title:'Café Docs',url:'https://example.com/docs'},{id:'folder',parentId:'bar',title:'Work',children:[{id:'b',parentId:'folder',title:'Other',url:'https://sub.example.org'}]}]},{id:'other',parentId:'root',title:'Other bookmarks',children:[]},{id:'managed',parentId:'root',title:'Managed',unmodifiable:'managed',children:[{id:'m',parentId:'managed',title:'Locked',url:'https://corp.example'}]}]}];
  const event=()=>{const ls=new Set();return{addListener:f=>ls.add(f),removeListener:f=>ls.delete(f),fire:(...a)=>ls.forEach(f=>f(...a)),get size(){return ls.size}}};
  const changed=event(),local={},sync={};
  const area=(data)=>({get:async keys=>Object.fromEntries((Array.isArray(keys)?keys:keys?[keys]:Object.keys(data)).map(k=>[k,structuredClone(data[k])])),set:async v=>{const diff={};for(const[k,x]of Object.entries(v)){diff[k]={newValue:x};data[k]=structuredClone(x)}changed.fire(diff,'local')},remove:async keys=>{for(const k of Array.isArray(keys)?keys:[keys])delete data[k]}});
  function find(id,list=roots){for(const n of list){if(n.id===id)return n;const x=find(id,n.children||[]);if(x)return x}}
  function detach(id){const n=find(id),p=find(n.parentId);p.children.splice(p.children.findIndex(x=>x.id===id),1);return n}
  const bookmarks={getTree:async()=>structuredClone(roots),get:async id=>[structuredClone(find(id))],create:async v=>{const p=find(v.parentId);if(!p)throw Error('Missing parent');const n={id:String(next++),...v,...(!v.url?{children:[]}: {})};p.children.push(n);bookmarks.onCreated.fire(n.id,n);return structuredClone(n)},update:async(id,v)=>{const n=find(id);Object.assign(n,v);bookmarks.onChanged.fire(id,v);return structuredClone(n)},move:async(id,v)=>{const n=detach(id);n.parentId=v.parentId;const children=find(v.parentId).children;children.splice(v.index??children.length,0,n);bookmarks.onMoved.fire(id,v);return structuredClone(n)},remove:async id=>{detach(id);bookmarks.onRemoved.fire(id)},removeTree:async id=>{detach(id);bookmarks.onRemoved.fire(id)}};
  for(const k of ['onCreated','onRemoved','onChanged','onMoved','onChildrenReordered','onImportEnded'])bookmarks[k]=event();
  return {bookmarks,storage:{local:area(local),sync:area(sync),onChanged:changed},local,sync};
}
