import {chromium, browserOptions} from './browser-runtime.mjs';
import {resolve} from 'node:path';import assert from 'node:assert/strict';
const errors=[];const browser=await chromium.launch(browserOptions);
try{
const context=await browser.newContext({viewport:{width:1440,height:1040},colorScheme:'light'});
const p=await context.newPage();p.setDefaultTimeout(7000);p.on('pageerror',e=>errors.push(e.message));
const url='file://'+resolve('innerDocumentation/design-directions/atelier.html');
await p.goto(url);await p.getByText('Library ready.',{exact:true}).waitFor();
assert.equal(await p.locator('html').getAttribute('data-design'),'atelier');
const dimensions=()=>p.evaluate(()=>({text:parseFloat(getComputedStyle(document.querySelector('.bookmark-title a')).fontSize),icon:parseFloat(getComputedStyle(document.querySelector('.bookmark-tile')).width),overflow:document.documentElement.scrollWidth>innerWidth}));
const before=await dimensions();
assert.equal(await p.locator('.bookmark').count(),40);
const sample=await p.evaluate(async()=>{const roots=await chrome.bookmarks.getTree(),folderTitles=[],tags=new Set();function walk(nodes){for(const n of nodes){if(n.children){folderTitles.push(n.title);walk(n.children)}}}walk(roots);for(const m of Object.values((await chrome.storage.local.get('bookmarks.metadata.v1'))['bookmarks.metadata.v1'].items))for(const tag of m.tags)tags.add(tag);return {folderTitles,tags:[...tags]}});assert.ok(sample.folderTitles.includes('Browser extensions'));assert.ok(sample.folderTitles.includes('Design systems'));assert.ok(sample.tags.length>=20);
assert.equal(await p.getByRole('button',{name:'Show filters',exact:true}).count(),1);await p.getByRole('button',{name:'Show filters',exact:true}).click();await p.getByLabel('Filter by domain').fill('figma.com');const filtered=await p.locator('.bookmark').count();assert.ok(filtered>0&&filtered<40);await p.getByRole('button',{name:'Hide filters',exact:true}).click();assert.equal(await p.locator('#filter-tray').isVisible(),false);assert.equal(await p.locator('#filters-active-count').innerText(),'1');
for(const view of ['List view','Grid view']){await p.getByRole('button',{name:view,exact:true}).click();assert.equal(await p.getByRole('button',{name:'Show filters',exact:true}).isVisible(),true);assert.equal(await p.locator('.bookmark').count(),filtered);}
await p.getByRole('button',{name:'Collections',exact:true}).click();assert.equal(await p.getByRole('button',{name:'Show filters',exact:true}).isVisible(),true);await p.getByRole('button',{name:'Collections',exact:true}).click();await p.getByRole('button',{name:'Show filters',exact:true}).click();assert.equal(await p.getByLabel('Filter by domain').inputValue(),'figma.com');await p.getByRole('button',{name:'Reset filters',exact:true}).click();assert.equal(await p.locator('.bookmark').count(),40);await p.reload();await p.getByText('Library ready.',{exact:true}).waitFor();assert.equal(await p.locator('#filter-tray').isVisible(),true);assert.equal(await p.getByRole('button',{name:'Hide filters',exact:true}).count(),1);await p.getByRole('button',{name:'Hide filters',exact:true}).click();
await p.getByRole('button',{name:'ui patterns',exact:true}).first().click();assert.equal(await p.locator('#filter-tray').isVisible(),true);await p.getByRole('button',{name:'Reset filters',exact:true}).click();await p.getByRole('button',{name:'Hide filters',exact:true}).click();

assert.equal(await p.locator('.workspace-tools').getByRole('button',{name:'Library tools',exact:true}).count(),0);
await p.getByRole('button',{name:'Settings',exact:true}).click();const d=p.locator('#settings-page');
await p.screenshot({path:'tests/settings-atelier.png',fullPage:true});
const libraryTools=d.getByRole('region',{name:'Library tools',exact:true});
for(const name of ['Export library','Import export','Undo last edit','Restore snapshot','Review cleanup'])assert.equal(await libraryTools.getByRole('button',{name,exact:true}).count(),1);
await libraryTools.getByRole('button',{name:'Review cleanup',exact:true}).click();await p.getByRole('dialog',{name:'Review duplicate links',exact:true}).waitFor();assert.equal(await d.isVisible(),false);await p.getByRole('dialog').getByRole('button',{name:'Cancel',exact:true}).click();await p.getByRole('button',{name:'Settings',exact:true}).click();
const downloadPromise=p.waitForEvent('download');await d.getByRole('button',{name:'Export library',exact:true}).click();const download=await downloadPromise;assert.equal(download.suggestedFilename(),'1sttab-bookmarks.json');
await d.locator('input[type=file]').setInputFiles(await download.path());await p.getByRole('dialog',{name:/^Import \d+ bookmarks and \d+ folders$/}).waitFor();assert.equal(await d.isVisible(),false);await p.getByRole('dialog').getByRole('button',{name:'Cancel',exact:true}).click();await p.getByRole('button',{name:'Settings',exact:true}).click();

for(const design of ['prism','studio','pop','enterprise','atelier']){await d.locator(`[name=design][value=${design}]`).check();assert.equal(await p.locator('html').getAttribute('data-design'),design);}
await d.getByLabel('Color mode',{exact:true}).selectOption('system');await p.emulateMedia({colorScheme:'dark'});await p.waitForFunction(()=>document.documentElement.dataset.theme==='dark');await p.emulateMedia({colorScheme:'light'});await p.waitForFunction(()=>document.documentElement.dataset.theme==='light');
await d.getByLabel('Color mode',{exact:true}).selectOption('light');await p.emulateMedia({colorScheme:'dark'});assert.equal(await p.locator('html').getAttribute('data-theme'),'light');
await d.getByLabel('Text size',{exact:true}).fill('1.4');const textOnly=await dimensions();assert.ok(textOnly.text>=before.text*1.39);assert.equal(textOnly.icon,before.icon);
await d.getByLabel('Icon size',{exact:true}).fill('1.5');const large=await dimensions();assert.ok(large.icon>=before.icon*1.49);assert.equal(large.text,textOnly.text);
await d.getByLabel('Spacing',{exact:true}).selectOption('compact');await d.locator('[name=showNotes]').uncheck();await d.locator('[name=reduceMotion]').check();await d.getByLabel('Default sort',{exact:true}).selectOption('title');await d.getByLabel('Bookmark view',{exact:true}).selectOption('list');
assert.equal(await p.locator('.bookmark-note').first().isVisible(),false);await d.getByRole('button',{name:'Back to library',exact:true}).click();assert.equal((await dimensions()).overflow,false);
await p.reload();await p.getByText('Library ready.',{exact:true}).waitFor();assert.equal(await p.locator('html').getAttribute('data-large-ui'),'true');assert.equal(await p.locator('html').getAttribute('data-density'),'compact');assert.equal(await p.locator('#sort-order').inputValue(),'title');assert.equal(await p.locator('html').evaluate(n=>n.style.getPropertyValue('--text-scale')),'1.4');
await p.setViewportSize({width:390,height:844});assert.equal((await dimensions()).overflow,false,'large list mobile overflow');await p.getByRole('button',{name:'Grid view',exact:true}).click();assert.equal((await dimensions()).overflow,false,'large cards mobile overflow');await p.getByRole('button',{name:'Collections',exact:true}).click();assert.equal(await p.locator('#folders').isVisible(),true);await p.getByRole('button',{name:'Close collections',exact:true}).click();
await p.getByRole('button',{name:'Show filters',exact:true}).click();assert.equal((await dimensions()).overflow,false,'visible filters mobile overflow');await p.getByRole('button',{name:'Hide filters',exact:true}).click();await p.getByRole('button',{name:'Settings',exact:true}).click();assert.equal(await d.evaluate(n=>n.scrollWidth<=n.clientWidth),true,'settings mobile overflow');await p.screenshot({path:'tests/settings-mobile.png',fullPage:true});
await d.getByRole('button',{name:'Reset appearance',exact:true}).click();assert.equal(await p.locator('html').getAttribute('data-design'),'enterprise');assert.equal(await d.getByLabel('Text size',{exact:true}).inputValue(),'1');assert.equal(await d.getByLabel('Default sort',{exact:true}).inputValue(),'title');await d.getByRole('button',{name:'Back to library',exact:true}).click();
await p.setViewportSize({width:1440,height:1040});await p.evaluate(async()=>chrome.storage.local.set({'bookmarks.preferences.v1':{design:'atelier',theme:'dark',textScale:1.2,iconScale:1.2}}));assert.equal(await p.locator('html').getAttribute('data-theme'),'dark');await p.getByRole('button',{name:'Settings',exact:true}).click();await p.screenshot({path:'tests/settings-dark.png',fullPage:true});await d.getByRole('button',{name:'Back to library',exact:true}).click();
for(const design of ['prism','atelier','studio','pop','enterprise'])for(const theme of ['light','dark']){await p.evaluate(async({design,theme})=>chrome.storage.local.set({'bookmarks.preferences.v1':{design,theme,textScale:1.4,iconScale:1.5}}),{design,theme});assert.equal((await dimensions()).overflow,false,`${design} ${theme} overflow`);if(theme==='dark'){const contrast=await p.evaluate(()=>{const luminance=color=>{const v=color.match(/[\d.]+/g).slice(0,3).map(Number).map(c=>{c/=255;return c<=.04045?c/12.92:((c+.055)/1.055)**2.4});return v[0]*.2126+v[1]*.7152+v[2]*.0722};const fg=luminance(getComputedStyle(document.querySelector('.bookmark-title')).color),bg=luminance(getComputedStyle(document.querySelector('.bookmark')).backgroundColor);return (Math.max(fg,bg)+.05)/(Math.min(fg,bg)+.05)});assert.ok(contrast>=4.5,`${design} title contrast ${contrast}`);}}
assert.deepEqual(errors,[]);console.log('Filters and 40-bookmark fixture passed; Settings passed: five designs, system mode, independent live scaling, persistence, storage updates, density/view/sort/notes/motion, reset, mobile overflow.');
}finally{await browser.close()}
